services:
  db:
    restart: always
    image: docker.io/library/postgres:16.3-alpine3.20
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: /run/secrets/db_name
      POSTGRES_USER: /run/secrets/db_user
      POSTGRES_PASSWORD: /run/secrets/db_password
    secrets:
    - db_name
    - db_user
    - db_password
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET: /run/secrets/django_secret
      DJANGO_DB_NAME: /run/secrets/db_name
      DJANGO_DB_USER: /run/secrets/db_user
      DJANGO_DB_PASSWORD: /run/secrets/db_password
      DJANGO_DB_HOST: db
      DJANGO_HOST: "*" # TODO Cross origin errors
    secrets:
    - db_name
    - db_user
    - db_password
    - django_secret
    depends_on:
      - db

secrets:
  db_name:
    file: /root/secrets/db_name.txt
  db_user:
    file: /root/secrets/db_user.txt
  db_password:
    file: /root/secrets/db_password.txt
  django_secret:
    file: /root/secrets/django_secret.txt
